### ISSUE TITLE
CameraRoll pictures are rotated 90 degrees when saved

### ISSUE THREAD

**Issue by atpunk** [react-community/react-native-image-picker#470]
iOS

Front camera is only correct when snapped with the device in Right orientation.

Rear camera is only correct when snapped with the device in Left orientation.

**Comment by fostertime** [comment]
Having the same issue.

**Comment by Romchik22** [comment]
I have same issue but only in Android. May be anyone now how i can solve this problem?

**Comment by lorenzodonini** [comment]
@Romchik22 Which device were you using?

**Comment by Romchik22** [comment]
@lorenzodonini LG G3

**Comment by hblab-nghianh** [comment]
Having the same issue with v0.26.3 and Sony Experia XZ

**Comment by angusmccloud** [comment]
Has anyone found a solution to this?

**Comment by rahimrahman** [comment]
@atpunk did you find a solution to your problem?

I'm using v0.26.3.

**Comment by angusmccloud** [comment]
@rahimrahman I wasn't able to find anything graceful. I'm doing a check to see if an image is incorrectly rotated, then passing that rotation to my API and rotating the image on the server (it could be done in the app, but I already had image processing happening on the server so I did it there).

`
  startImagePicker() {
    ImagePicker.showImagePicker(options, (response) => {
      if (response.didCancel) {
//        Alert.alert("User cancelled image picker");
        console.log('User cancelled image picker');
      }
      else if (response.error) {
//        Alert.alert("ImagePicker Error: " + response.error);
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
//        Alert.alert(response.originalRotation);
        if(Platform.OS === 'android'){
//          console.log(response);
          if(response.originalRotation !== 0 && response.isVertical === false && response.width > response.height){
            var rotationDegrees = response.originalRotation;
//            console.log("Need to Rotate Image");
          }
          else{
            var rotationDegrees = 0;
//            console.log("Image does not need to be rotated");
          }

//          console.log(response.height);
//          console.log(response.width);
//          console.log(response.type);
//          console.log(response.isVertical);
//          console.log(response.originalRotation);
        }
        else{
          var rotationDegrees = 0;
//          console.log("Not Android, no image rotation");
        }
....`

**Comment by rahimrahman** [comment]
@angusmccloud Interesting part is the image is not rotated when I first took the photo with my camera.  The photo uploaded correctly.  However when I use storageOptions.cameraRoll = true, and open up camera roll later, the image that was captured earlier is saved and is rotated 90 degrees.

**Comment by angusmccloud** [comment]
@rahimrahman The rotation behavior isn't consistent across all android devices (some will post to an API rotated and some won't). I wasn't able to figure out if that was OS specific or what was causing it (hence the various criteria in that IF statement).

I also agree - saving vertical images to the camera roll are coming in rotated for me as well. I gave up on figuring that one out...

**Comment by rahimrahman** [comment]
@angusmccloud Understood.  Thanks for your snippet of code handling the rotated image issue.  It might help me when I test this on various android device(s).

**Comment by wkwyatt** [comment]
@angusmccloud How were you able to actually manipulate and rotate the image on the app so that the image won't post to the API rotated. 

This is my code but it doesn't seem to work..
```js
let androidImageData = {}
if (Platform.OS === 'android') {
    if (response.originalRotation !== 0 && response.isVertical === false && response.width > response.height) {
        androidImageData = {...response, originalRotation: 180, isVertical: true};
    }
}

this.setState({ selectedImage: Platform.OS === 'android' ? androidImageData : response });

```

Then the upload to the API 
```js
const file = {
    .append('file', {
            uri: uri,
            name: fileName,
            size: fileSize,
            type: fileTypeUse,
            originalRotation: originalRotation,
            isVertical: isVertical
}

Axios({
            method: 'post',
            url: `${API_URL}`,
            data: file,
            withCredentials: false,
            headers: { 'Content-Disposition': `attachment; filename=${file.name}`}
}).then((result) => {});
```

**Comment by angusmccloud** [comment]
@wkwyatt I did the rotation on the API/Server side since I was already doing image processing there and I knew how to rotate it in PHP (aka I didn't feel like figuring it out in JS/RN). So I pass the rotationDegrees variable back to the API so it knows if the image needs to rotate.

Sorry I don't have a better answer...

**Comment by doochik** [comment]
I've fixed some issues with photo orientation in iOS
https://github.com/facebook/react-native/pull/15060
https://github.com/facebook/react-native/pull/15690

It's may be related to this bug

**Comment by FuYaoDe** [comment]
https://github.com/react-community/react-native-image-picker/blob/develop/ios/ImagePickerManager.m#L403

change to 

```
[library writeImageToSavedPhotosAlbum:image.CGImage orientation:(ALAssetOrientation)[image imageOrientation] completionBlock:^(NSURL *assetURL, NSError *error) {
```
fix @rahimrahman problem

**Comment by leiz-me** [comment]
@FuYaoDe @teradiot
When does the release version that get this problem fixed come out?

Currently using 0.26.7 and image keep rotating after capture on iOS.

**Comment by JayricMok** [comment]
I'm using version 0.26.7, and this issue still exist. This issue cause a very base user experience, if anyone have the solution please kindly share. Thanks you very much !

**Comment by JayricMok** [comment]
@leiz-me this solution fixed my ios saved with 90 degrees changed problem.

    var optionsIOS = {
      title: 'Choose Avatar',
      cancelButtonTitle:'Cancel',
      takePhotoButtonTitle:'Capture Photo',
      chooseFromLibraryButtonTitle:'Browse from Gallery',
      quality:0.5,
      storageOptions: {
        cameraRoll: true,
        skipBackup: true,
        waitUntilSaved:true
      }
    };

**Comment by leiz-me** [comment]
@JayricMok 
Thanks for replying.
But still, not work for me.
I am waiting for the team to update their release since some solution has been made from this [link](https://github.com/teradiot/react-native-image-picker/commit/edd247d88887c9b2982bb2fa3cd8344f592a0544) they mentioned.

**Comment by IcebergRage** [comment]
Any solution ?

**Comment by roycclu** [comment]
problem still exists. 
The image response returned gives photo in the correct orientation, however, the photo saved to camera roll is incorrectly rotated 90 degrees. 

@FuYaoDe 
i inserted your code but the problem still persists. anyone else tried it and it worked?

**Comment by hubertli1991** [comment]
Hi @charpeni, @paweljaneczek,

The problem still exists.
I'm using v0.27.1 which has the updates from #887.
I just took a picture and saw that the image in the camera roll is still oriented 90.
Any help would be greatly appreciated.

Device: iPhone 7 iOs 11

**Comment by leiz-me** [comment]
any update now?

**Comment by felipap** [comment]
Anybody?

**Comment by hubertli1991** [comment]
There's an explanation in #955

**Comment by cyberdude** [comment]
Just curious. Doesn't this make the library not useful ?
